### ISSUE TITLE
Lambda should change boolean values

### ISSUE THREAD

**Issue by fillman** [dchelimsky/rspec-rails#16]
It seems like this wont work:
(debugging shows that lambda { simply_another_user.**send** :active } calls 2 times in @actual_before and @actual_after but returns true anyway even after calling a block). Any ideas?

``` ruby
if "should toggle a user" do
    simply_another_user = Factory(:user)
    simply_another_user.active.should be_true

    # Toggle from true to false
    debugger
    lambda {
      post :toggle, :id => simply_another_user
    }.should change(simply_another_user, :active)
end
```

**Comment by dchelimsky** [comment]
The post affects the underlying data, but not the `simply_another_user` object. You could do this instead:

``` ruby
lambda {
  post :toggle, :id => simply_another_user
}.should change { simply_another_user.reload.active }
```

I'd be more inclined to do something like this:

``` ruby
user = Factory(:user, :active => true)
post :toggle, :id => user
User.find(user.id).active.should be_false
```

**Comment by fillman** [comment]
Thanks David, but why did you like the second variant? The first is much "readable" I think.

As I mentioned I came up with this:

``` ruby
lambda {
      post :toggle, :id => simply_another_user
}.should change { simply_another_user.reload.active }.from(true).to(false)
```

As it reads better. Thanks again David. Appreciate your work and time.

**Comment by dchelimsky** [comment]
"readability" is subjective, and you're not comparing the entire example. Compare these:

``` ruby
user = Factory(:user)
user.active.should be_true
lambda {
  post :toggle, :id => simply_another_user
}.should change { simply_another_user.reload.active }

# vs

user = Factory(:user, :active => true)
post :toggle, :id => user
User.find(user.id).active.should be_false
```

To me, the latter is easier to follow because it's more concise, more declarative (create a user with :active => true rather than setting an expectation that it's true before the event in the example), more truthful (in reality, the post does not touch the same object), and doesn't rely on idiosyncrasies of ActiveRecord (i.e. `reload`). But that's for me. If you think the former is more readable, than that's the form you should use because you're the one that's going to have to read it.
